const movies = [
    { title: 'Inception', genre: 'Fantascienza' },
    { title: 'Il Padrino', genre: 'Thriller' },
    { title: 'Titanic', genre: 'Romantico' },
    { title: 'Batman', genre: 'Azione' },
    { title: 'Interstellar', genre: 'Fantascienza' },
    { title: 'Pulp Fiction', genre: 'Thriller' },
    { title: 'La La Land', genre: 'Musicale' },
    { title: 'Il Signore degli Anelli: La Compagnia dell’Anello', genre: 'Fantasy' },
    { title: 'Forrest Gump', genre: 'Drammatico' },
    { title: 'Shrek', genre: 'Animazione' },
    { title: 'Mad Max: Fury Road', genre: 'Azione' },
    { title: 'Parasite', genre: 'Drammatico' },
    { title: 'Indiana Jones e i Predatori dell’Arca Perduta', genre: 'Avventura' },
    { title: 'Matrix', genre: 'Fantascienza' },
    { title: 'Coco', genre: 'Animazione' },
    { title: 'La Forma dell’Acqua', genre: 'Fantasy' },
    { title: 'Whiplash', genre: 'Drammatico' },
    { title: 'Alien', genre: 'Horror' },
    { title: 'Il Grande Lebowski', genre: 'Commedia' },
    { title: 'Gladiator', genre: 'Storico' },
    { title: 'Toy Story', genre: 'Animazione' },
    { title: 'Joker', genre: 'Drammatico' },
    { title: 'Dune', genre: 'Fantascienza' },
    { title: 'Il Re Leone', genre: 'Animazione' },
    { title: 'The Social Network', genre: 'Biografico' },
    { title: 'La Città Incantata', genre: 'Fantasy' },
    { title: 'Inside Out', genre: 'Animazione' },
    { title: 'The Truman Show', genre: 'Drammatico' },
    { title: 'Blade Runner', genre: 'Fantascienza' },
    { title: 'Jurassic Park', genre: 'Avventura' },
    { title: 'The Wolf of Wall Street', genre: 'Biografico' },
    { title: 'Up', genre: 'Animazione' },
    { title: 'Gravity', genre: 'Fantascienza' },
    { title: 'The Hateful Eight', genre: 'Western' },
    { title: 'The Pianist', genre: 'Storico' },
    { title: 'Logan', genre: 'Azione' },
    { title: 'A Beautiful Mind', genre: 'Biografico' },
    { title: 'La Vita è Bella', genre: 'Drammatico' },
    { title: 'Get Out', genre: 'Horror' },
    { title: 'Black Panther', genre: 'Azione' }
];


export default movies;